#!/bin/bash

PFBENCH="$PWD/benchmark"
cd $PFBENCH

PATH=$PATH:$PFBENCH/scripts/execution:$PFBENCH/scripts/analysis
NUM_CONTAINERS=$1
TIMEOUT=$(( ${2:-1440} * 60))
SKIPCOUNT="${SKIPCOUNT:-1}"
TEST_TIMEOUT="${TEST_TIMEOUT:-5000}"

export TARGET_LIST=$3
export FUZZER_LIST=$4
export EXPERIMENT_ID="${5:-}"

if [[ "x$NUM_CONTAINERS" == "x" ]] || [[ "x$TIMEOUT" == "x" ]] || [[ "x$TARGET_LIST" == "x" ]] || [[ "x$FUZZER_LIST" == "x" ]]
then
    echo "Usage: $0 NUM_CONTAINERS TIMEOUT TARGET FUZZER [EXPERIMENT_ID]"
    exit 1
fi

PFBENCH=$PFBENCH PATH=$PATH LLM_URL="$LLM_URL" LLM_TOKEN="$LLM_TOKEN" LLM_MODEL="$LLM_MODEL" AFL_LLM_VALIDATION="$AFL_LLM_VALIDATION" AFL_LLM_VALIDATION_PERMISSIVE="$AFL_LLM_VALIDATION_PERMISSIVE" AFL_LLM_VALIDATION_STRICT="$AFL_LLM_VALIDATION_STRICT" AFL_LLM_POST_GAIN="$AFL_LLM_POST_GAIN" AFL_LLM_FEEDBACK="$AFL_LLM_FEEDBACK" AFL_LLM_FEEDBACK_MAX_RETRIES="$AFL_LLM_FEEDBACK_MAX_RETRIES" AFL_LLM_SKIP_STARTUP="$AFL_LLM_SKIP_STARTUP" EXPERIMENT_ID="$EXPERIMENT_ID" NUM_CONTAINERS=$NUM_CONTAINERS TIMEOUT=$TIMEOUT SKIPCOUNT=$SKIPCOUNT TEST_TIMEOUT=$TEST_TIMEOUT scripts/execution/profuzzbench_exec_all.sh ${TARGET_LIST} ${FUZZER_LIST}